//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarotType.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarotType.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #eeeee4
        ///English.
        /// </summary>
    
        internal static string French
        {
            get
            {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        internal static string Finnish
        {
            get
            {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        internal static string Swedish
        {
            get
            {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        internal static string Armenian
        {
            get
            {
                return ResourceManager.GetString("Armenian", resourceCulture);
            }
        }
        internal static string Chinese
        {
            get
            {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        internal static string Azerbaijani
        {
            get
            {
                return ResourceManager.GetString("Azerbaijani", resourceCulture);
            }
        }
        internal static string English
        {
            get
            {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        internal static string Greek
        {
            get
            {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        internal static string Kurdish
        {
            get
            {
                return ResourceManager.GetString("Kurdish", resourceCulture);
            }
        }
        internal static string Persian
        {
            get
            {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        internal static string Spanish
        {
            get
            {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        internal static string Turkish
        {
            get
            {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        internal static string Arabic
        {
            get
            {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        internal static string Serbian      
        {
            get
            {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        internal static string Georgian
        {
            get
            {
                return ResourceManager.GetString("Georgian", resourceCulture);      
            }
        }
    }
}
